-- Build a single AutoChart-like contour surface from both the precise
-- 10 metre bathymetry and the broad 25 metre coverage. Unlike the older
-- raster-style contour builders, this uses local Delaunay triangulation and
-- therefore does not require four complete neighbouring grid cells.

create table public.sonar_autochart_contours (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id uuid not null references public.sonar_import_jobs(id) on delete cascade,
  tile_x integer not null,
  tile_y integer not null,
  depth_m real not null check (depth_m >= 0),
  interval_m real not null check (interval_m > 0),
  confidence real not null check (confidence between 0 and 1),
  geometry geometry(LineString, 4326) not null,
  created_at timestamptz not null default now()
);

create index sonar_autochart_contours_geometry_gix
  on public.sonar_autochart_contours using gist (geometry);
create index sonar_autochart_contours_job_depth_idx
  on public.sonar_autochart_contours (user_id, job_id, depth_m);
create index sonar_autochart_contours_job_tile_idx
  on public.sonar_autochart_contours (job_id, tile_x, tile_y);

alter table public.sonar_autochart_contours enable row level security;
revoke all on table public.sonar_autochart_contours
  from public, anon, authenticated;
grant all on table public.sonar_autochart_contours to service_role;

create or replace function public.sonar_prepare_autochart_contours(
  p_job_id uuid,
  p_user_id uuid
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  deleted_count bigint;
begin
  if not exists (
    select 1
    from public.sonar_import_jobs
    where id = p_job_id
      and user_id = p_user_id
  ) then
    raise exception 'Sonar job not found';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_job_id::text || ':autochart:prepare', 0)
  );

  delete from public.sonar_autochart_contours
  where job_id = p_job_id
    and user_id = p_user_id;

  get diagnostics deleted_count = row_count;
  return deleted_count;
end
$$;

create or replace function public.sonar_build_autochart_contour_bucket(
  p_job_id uuid,
  p_user_id uuid,
  p_bucket smallint,
  p_interval_m real default 0.5,
  p_max_gap_m real default 175
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
set statement_timeout = '5min'
as $$
declare
  inserted_count bigint;
begin
  if p_bucket not between 0 and 63 then
    raise exception 'Invalid AutoChart contour bucket';
  end if;
  if p_interval_m < 0.25 or p_interval_m > 20 then
    raise exception 'Invalid AutoChart contour interval';
  end if;
  if p_max_gap_m < 25 or p_max_gap_m > 300 then
    raise exception 'Invalid AutoChart interpolation distance';
  end if;
  if not exists (
    select 1
    from public.sonar_import_jobs
    where id = p_job_id
      and user_id = p_user_id
  ) then
    raise exception 'Sonar job not found';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      p_job_id::text || ':autochart:bucket:' || p_bucket::text,
      0
    )
  );

  delete from public.sonar_autochart_contours
  where job_id = p_job_id
    and user_id = p_user_id
    and ((tile_x # tile_y) & 63) = p_bucket;

  with depth_percentile as materialized (
    select percentile_cont(0.99) within group (order by avg_depth_m)
      as p99_depth_m
    from public.sonar_bathymetry_coverage_cells
    where job_id = p_job_id
      and user_id = p_user_id
      and avg_depth_m between 0.2 and 200
  ),
  depth_limit as materialized (
    select least(
      200,
      coalesce(p99_depth_m, 50) + greatest(10, coalesce(p99_depth_m, 50) * 0.5)
    ) as max_depth_m
    from depth_percentile
  ),
  tiles as materialized (
    select distinct
      floor((grid_x * 25.0) / 1000)::integer as tile_x,
      floor((grid_y * 25.0) / 1000)::integer as tile_y
    from public.sonar_bathymetry_coverage_cells
    where job_id = p_job_id
      and user_id = p_user_id
      and (
        (
          floor((grid_x * 25.0) / 1000)::integer
          # floor((grid_y * 25.0) / 1000)::integer
        ) & 63
      ) = p_bucket
  ),
  masks as materialized (
    select
      t.tile_x,
      t.tile_y,
      st_unaryunion(
        st_collect(
          st_setsrid(
            st_makeenvelope(
              c.grid_x * 25.0,
              c.grid_y * 25.0,
              (c.grid_x + 1) * 25.0,
              (c.grid_y + 1) * 25.0
            ),
            3857
          )
        )
      ) as geometry
    from tiles t
    join public.sonar_bathymetry_coverage_cells c
      on c.job_id = p_job_id
      and c.user_id = p_user_id
      and floor((c.grid_x * 25.0) / 1000)::integer = t.tile_x
      and floor((c.grid_y * 25.0) / 1000)::integer = t.tile_y
    group by t.tile_x, t.tile_y
  ),
  nodes as materialized (
    select
      t.tile_x,
      t.tile_y,
      (b.grid_x + 0.5) * 10.0 as x,
      (b.grid_y + 0.5) * 10.0 as y,
      b.avg_depth_m::double precision as depth_m
    from tiles t
    join public.sonar_bathymetry_cells b
      on b.job_id = p_job_id
      and b.user_id = p_user_id
      and b.resolution_m = 10
      and (b.grid_x + 0.5) * 10.0
        between t.tile_x * 1000.0 - p_max_gap_m
          and (t.tile_x + 1) * 1000.0 + p_max_gap_m
      and (b.grid_y + 0.5) * 10.0
        between t.tile_y * 1000.0 - p_max_gap_m
          and (t.tile_y + 1) * 1000.0 + p_max_gap_m
    cross join depth_limit l
    where b.confidence >= 0.15
      and b.avg_depth_m between 0.2 and l.max_depth_m
      and b.max_depth_m - b.min_depth_m
        <= greatest(8, b.avg_depth_m * 1.5)

    union all

    select
      t.tile_x,
      t.tile_y,
      (c.grid_x + 0.5) * 25.0 as x,
      (c.grid_y + 0.5) * 25.0 as y,
      c.avg_depth_m::double precision as depth_m
    from tiles t
    join public.sonar_bathymetry_coverage_cells c
      on c.job_id = p_job_id
      and c.user_id = p_user_id
      and (c.grid_x + 0.5) * 25.0
        between t.tile_x * 1000.0 - p_max_gap_m
          and (t.tile_x + 1) * 1000.0 + p_max_gap_m
      and (c.grid_y + 0.5) * 25.0
        between t.tile_y * 1000.0 - p_max_gap_m
          and (t.tile_y + 1) * 1000.0 + p_max_gap_m
    cross join depth_limit l
    where c.confidence >= 0.1
      and c.avg_depth_m between 0.2 and l.max_depth_m
      and c.max_depth_m - c.min_depth_m
        <= greatest(10, c.avg_depth_m * 1.8)
      and not exists (
        select 1
        from public.sonar_bathymetry_cells d
        where d.job_id = c.job_id
          and d.user_id = c.user_id
          and d.resolution_m = 10
          and d.grid_x = floor(((c.grid_x + 0.5) * 25.0) / 10)::bigint
          and d.grid_y = floor(((c.grid_y + 0.5) * 25.0) / 10)::bigint
      )
  ),
  triangulations as materialized (
    select
      n.tile_x,
      n.tile_y,
      st_delaunaytriangles(
        st_collect(
          st_setsrid(st_makepoint(n.x, n.y, n.depth_m), 3857)
        ),
        0,
        0
      ) as geometry
    from nodes n
    group by n.tile_x, n.tile_y
    having count(*) >= 3
  ),
  triangle_dump as materialized (
    select
      t.tile_x,
      t.tile_y,
      (st_dump(t.geometry)).geom as geometry
    from triangulations t
  ),
  vertices as materialized (
    select
      row_number() over (
        partition by d.tile_x, d.tile_y
        order by st_xmin(d.geometry), st_ymin(d.geometry), st_xmax(d.geometry)
      ) as triangle_id,
      d.tile_x,
      d.tile_y,
      st_pointn(st_exteriorring(d.geometry), 1) as a,
      st_pointn(st_exteriorring(d.geometry), 2) as b,
      st_pointn(st_exteriorring(d.geometry), 3) as c
    from triangle_dump d
  ),
  triangles as materialized (
    select
      v.*,
      greatest(
        st_distance(v.a, v.b),
        st_distance(v.b, v.c),
        st_distance(v.c, v.a)
      ) as max_edge_m
    from vertices v
  ),
  valid_triangles as materialized (
    select
      t.*,
      greatest(
        0.15,
        least(1, 1 - (t.max_edge_m / p_max_gap_m) * 0.8)
      )::real as confidence
    from triangles t
    where t.max_edge_m <= p_max_gap_m
      and greatest(st_z(t.a), st_z(t.b), st_z(t.c))
        - least(st_z(t.a), st_z(t.b), st_z(t.c))
        <= greatest(
          14,
          least(st_z(t.a), st_z(t.b), st_z(t.c)) * 2.2
        )
  ),
  levels as materialized (
    select
      t.*,
      (level_index * p_interval_m)::double precision as depth_m
    from valid_triangles t
    cross join lateral generate_series(
      ceil(least(st_z(t.a), st_z(t.b), st_z(t.c)) / p_interval_m)::integer,
      floor(greatest(st_z(t.a), st_z(t.b), st_z(t.c)) / p_interval_m)::integer
    ) as level_index
  ),
  crossings as materialized (
    select
      l.tile_x,
      l.tile_y,
      l.triangle_id,
      l.depth_m,
      l.confidence,
      edge.edge_no,
      st_setsrid(
        st_makepoint(
          edge.xa + (edge.xb - edge.xa)
            * ((l.depth_m - edge.da) / nullif(edge.db - edge.da, 0)),
          edge.ya + (edge.yb - edge.ya)
            * ((l.depth_m - edge.da) / nullif(edge.db - edge.da, 0))
        ),
        3857
      ) as point
    from levels l
    cross join lateral (
      values
        (1, st_x(l.a), st_y(l.a), st_z(l.a), st_x(l.b), st_y(l.b), st_z(l.b)),
        (2, st_x(l.b), st_y(l.b), st_z(l.b), st_x(l.c), st_y(l.c), st_z(l.c)),
        (3, st_x(l.c), st_y(l.c), st_z(l.c), st_x(l.a), st_y(l.a), st_z(l.a))
    ) as edge(edge_no, xa, ya, da, xb, yb, db)
    where edge.da <> edge.db
      and l.depth_m >= least(edge.da, edge.db)
      and l.depth_m < greatest(edge.da, edge.db)
  ),
  triangle_segments as materialized (
    select
      c.tile_x,
      c.tile_y,
      c.triangle_id,
      c.depth_m,
      min(c.confidence)::real as confidence,
      st_makeline(array_agg(c.point order by c.edge_no)) as geometry
    from crossings c
    group by c.tile_x, c.tile_y, c.triangle_id, c.depth_m
    having count(*) = 2
  ),
  clipped as materialized (
    select
      s.tile_x,
      s.tile_y,
      s.depth_m,
      s.confidence,
      st_collectionextract(
        st_intersection(s.geometry, m.geometry),
        2
      ) as geometry
    from triangle_segments s
    join masks m using (tile_x, tile_y)
    where s.geometry && m.geometry
  ),
  merged as materialized (
    select
      c.tile_x,
      c.tile_y,
      c.depth_m,
      min(c.confidence)::real as confidence,
      st_linemerge(
        st_unaryunion(
          st_collect(st_snaptogrid(c.geometry, 0.01))
        )
      ) as geometry
    from clipped c
    where not st_isempty(c.geometry)
      and st_length(c.geometry) > 0.1
    group by c.tile_x, c.tile_y, c.depth_m
  ),
  dumped as materialized (
    select
      m.tile_x,
      m.tile_y,
      m.depth_m,
      m.confidence,
      (st_dump(st_collectionextract(m.geometry, 2))).geom as geometry
    from merged m
  ),
  smoothed as (
    select
      d.tile_x,
      d.tile_y,
      d.depth_m,
      d.confidence,
      case
        when st_npoints(d.geometry) >= 3 then
          st_chaikinsmoothing(
            st_simplifypreservetopology(d.geometry, 0.25),
            1,
            true
          )
        else d.geometry
      end as geometry
    from dumped d
    where not st_isempty(d.geometry)
      and st_length(d.geometry) >= 4
  )
  insert into public.sonar_autochart_contours (
    user_id,
    job_id,
    tile_x,
    tile_y,
    depth_m,
    interval_m,
    confidence,
    geometry
  )
  select
    p_user_id,
    p_job_id,
    s.tile_x,
    s.tile_y,
    s.depth_m::real,
    p_interval_m,
    s.confidence,
    st_transform(s.geometry, 4326)
  from smoothed s
  where not st_isempty(s.geometry)
    and geometrytype(s.geometry) = 'LINESTRING'
    and st_npoints(s.geometry) >= 2;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end
$$;

create or replace function public.sonar_autochart_contour_vector_tile(
  p_user_id uuid,
  p_z integer,
  p_x integer,
  p_y integer
)
returns text
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  tile_bounds geometry;
  geographic_bounds geometry;
  simplification_m double precision;
  contour_tile bytea;
begin
  if p_z < 0 or p_z > 22 or p_x < 0 or p_y < 0 then
    raise exception 'Invalid tile coordinate';
  end if;

  tile_bounds := st_tileenvelope(p_z, p_x, p_y);
  geographic_bounds := st_transform(tile_bounds, 4326);
  simplification_m := case
    when p_z <= 10 then 12
    when p_z <= 12 then 4
    when p_z <= 14 then 1
    else 0.25
  end;

  with contour_features as (
    select
      c.depth_m as depth,
      c.interval_m as interval,
      c.confidence,
      (mod(round(c.depth_m * 2)::integer, 5) = 0)::integer as major,
      st_asmvtgeom(
        st_simplifypreservetopology(
          st_transform(c.geometry, 3857),
          simplification_m
        ),
        tile_bounds,
        4096,
        64,
        true
      ) as geom
    from public.sonar_autochart_contours c
    join public.sonar_import_jobs j on j.id = c.job_id
    where c.user_id = p_user_id
      and j.status in ('completed', 'completed_with_errors')
      and c.geometry && geographic_bounds
      and (
        p_z >= 15
        or (p_z = 14 and mod(round(c.depth_m * 2)::integer, 2) = 0)
        or (p_z = 13 and mod(round(c.depth_m * 2)::integer, 5) = 0)
        or (p_z between 11 and 12 and mod(round(c.depth_m * 2)::integer, 10) = 0)
        or (p_z <= 10 and mod(round(c.depth_m * 2)::integer, 20) = 0)
      )
  )
  select coalesce(
    st_asmvt(contour_features, 'autochart_contours', 4096, 'geom'),
    ''::bytea
  )
  into contour_tile
  from contour_features;

  return encode(coalesce(contour_tile, ''::bytea), 'base64');
end
$$;

revoke all on function public.sonar_prepare_autochart_contours(uuid, uuid)
  from public, anon, authenticated;
revoke all on function public.sonar_build_autochart_contour_bucket(
  uuid, uuid, smallint, real, real
) from public, anon, authenticated;
revoke all on function public.sonar_autochart_contour_vector_tile(
  uuid, integer, integer, integer
) from public, anon, authenticated;

grant execute on function public.sonar_prepare_autochart_contours(uuid, uuid)
  to service_role;
grant execute on function public.sonar_build_autochart_contour_bucket(
  uuid, uuid, smallint, real, real
) to service_role;
grant execute on function public.sonar_autochart_contour_vector_tile(
  uuid, integer, integer, integer
) to service_role;
